# -*- coding: utf-8 -*-
"""test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nnq9knCfWQhdlN2IBHkvqrdmvnNijeP4
"""

import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="Two Visuals Demo", layout="centered")

st.title("📊 Streamlit Visualization App")

# ---- Load Example Data ----
# Replace this with your dataset
df = pd.DataFrame({
    "Category": ["A", "A", "B", "B", "C", "C"],
    "Subgroup": ["X", "Y", "X", "Y", "X", "Y"],
    "Value1": [10, 15, 20, 25, 30, 35],
    "Value2": [5, 7, 15, 20, 25, 28]
})

# ---- Scatter Plot ----
st.subheader("🔹 Scatter Plot")
scatter = alt.Chart(df).mark_circle(size=100).encode(
    x="Value1",
    y="Value2",
    color="Category",
    tooltip=["Category", "Subgroup", "Value1", "Value2"]
).interactive()
st.altair_chart(scatter, use_container_width=True)

# ---- Clustered Column Chart ----
st.subheader("🔹 Clustered Column Chart")
bar = alt.Chart(df).mark_bar().encode(
    x=alt.X("Category:N", title="Category"),
    y=alt.Y("Value1:Q", title="Value"),
    color="Subgroup:N",
    column="Subgroup:N"
).properties(width=150)
st.altair_chart(bar, use_container_width=True)
