# -*- coding: utf-8 -*-
"""test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nnq9knCfWQhdlN2IBHkvqrdmvnNijeP4
"""

import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="Test Streamlit App", layout="centered")

st.title("📊 Streamlit Test App")
st.write("This is a quick demo app to test Streamlit in Colab or locally.")

# User input
name = st.text_input("Enter your name:")
if name:
    st.success(f"Hello {name}, welcome to Streamlit! 🎉")

# Slider demo
age = st.slider("Select your age:", 0, 100, 25)
st.write(f"✅ Your age is {age}")

# Random DataFrame
st.subheader("Random DataFrame Example")
df = pd.DataFrame(np.random.randn(10, 3), columns=["A", "B", "C"])
st.dataframe(df)

# Chart
st.subheader("Line Chart Example")
st.line_chart(df)